[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true


[workspace]
package = { edition = "2024", version = "0.1.0" }
resolver = "2"
members = [
  "platform/wl",

  "crates/renderer",
  "crates/graphics",
  "crates/graphics_v2",
  "crates/atlas",
  "crates/canvas",
  "crates/input",
  "crates/gui",
  "crates/gui_reactive",
  "crates/gui_reactive_static",
  "platform/wl",
  "crates/wgpu_renderer",
]
default-members = ["platform/wl"]

[workspace.dependencies]
renderer = { path = "./crates/renderer" }
atlas = { path = "./crates/atlas" }
canvas = { path = "./crates/canvas" }

graphics = { path = "./crates/graphics" }
graphics_v2 = { path = "./crates/graphics_v2" }
input = { path = "./crates/input", default-features = false }
gui = { path = "./crates/gui" }
gui_reactive = { path = "./crates/gui_reactive" }

anyhow = "1.0.98"
clap = { version = "4.5.45", features = ["derive"] }
color-eyre = "0.6.5"
bincode = "2.0.1"
thiserror = "2.0.12"

async-executor = "1.13.2"
futures-lite = "2.6.1"

bytemuck = "1.23.1"
bitflags = "2.9.1"
color = { version = "0.3.1", features = ["serde", "bytemuck"] }
smithay-client-toolkit = { version = "0.20.0", default-features = false }
wayland-backend = { version = "0.3.10", default-features = false }
lyon = { version = "1.0.1", features = ["serialization"] }
serde = { version = "1.0.219", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
tokio = { version = "1.47.0", features = ["full"] }
tracing = "0.1.41"
log = "0.4.28"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
wgpu = { version = "26.0.1", default-features = false, features = [
  "std",
  "parking_lot",
  "vulkan",
  "wgsl",
  "webgpu",
] }

euclid = "0.22.11"

# cosmic-text = { version = "0.14.2", features = ["vi"] }
guillotiere = "0.6.2"
usvg = "0.45.1"
taffy = "0.9.1"


rustc-hash = "2.1.1"

accesskit = { version = "0.21.0" }
rstar = { version = "0.12.2" }


calloop = "0.14.3"
calloop-wayland-source = "0.4.1"

swash = { version = "0.2.5", features = ["scale"] }
parley = { version = "0.5.0" }
# fontique = { version = "0.5.0" }
# peniko = { version = "0.4.0" }
# kurbo = { version = "0.11.2" }

[patch.crates-io]
taffy = { path = "./crates/taffy_rounding_patch" }
# calloop = { path = "./crates/calloop_schedule_sync" }
