[package]
name = "canvas"
version = { workspace = true }
edition = { workspace = true }


[dependencies]
graphics = { workspace = true }
gui = { workspace = true }
gui_reactive = { workspace = true }
input = { workspace = true, features = ["serde"] }
renderer = { workspace = true }

anyhow = { workspace = true }
bytemuck = { workspace = true }
lyon = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }

tracing = { workspace = true }

color = { workspace = true }
wgpu = { workspace = true }
euclid = { workspace = true }
