[package]
name = "wgpu_renderer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
gui = { workspace = true, optional = true }
graphics = { workspace = true, features = ["parley", "lyon"] }
atlas = { workspace = true }

euclid = { workspace = true }
lyon = { workspace = true }

bytemuck = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

parley = { workspace = true }
swash = { workspace = true }
serde = { workspace = true, optional = true, features = ["rc"] }

color = { workspace = true }
wgpu = { workspace = true }

slotmap = { workspace = true }

profiling = { workspace = true }

[features]
default = ["gui"]
