[package]
name = "gui_reactive"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
input = { workspace = true }
graphics = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

accesskit = { workspace = true, optional = true }
slotmap = "1.0.7"
sycamore-reactive = "0.9.2"
taffy = { workspace = true }

color = { workspace = true }
euclid = { workspace = true }


[features]
default = ["accesskit"]
accesskit = ["dep:accesskit"]
