[package]
name = "gui_reactive"
version = { workspace = true }
edition = { workspace = true }
default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"
test = false
bench = false

[[bin]]
name = "rg_test"
path = "src/reactive_graph_test.rs"
test = false
bench = false


[dependencies]
input = { workspace = true }
graphics = { workspace = true }

color = { workspace = true }
lyon = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

euclid = { workspace = true }
taffy = { workspace = true }

accesskit = { workspace = true, optional = true }
# rstar = { workspace = true }

reactive_graph = { version = "0.2.6", features = ["effects"] }
reactive_stores = "0.2.5"
reactive_stores_macro = "0.2.6"
erased = "0.1.2"
next_tuple = "0.1.0"
paste = "1.0.15"

any_spawner = { version = "0.3.0", features = ["tokio"] }
tokio = { version = "1.47.1", features = ["full"] }


[features]
default = ["accesskit"]
accesskit = ["dep:accesskit"]
