[package]
name = "wl"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
# Internal dependencies
canvas = { workspace = true }
renderer_old = { workspace = true }
input = { workspace = true, features = ["sctk", "serde"] }

# Math types
euclid = { workspace = true }

async-executor = { workspace = true }
futures-lite = { workspace = true }
tokio = { workspace = true, features = ["full"] }

tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }

thiserror = { workspace = true }
color-eyre = { workspace = true }

clap = { workspace = true }
# For IPC over unix domain sockets.
rkyv = { workspace = true }


calloop = { workspace = true, features = ["executor"] }
calloop-wayland-source = { workspace = true }
smithay-client-toolkit = { workspace = true, features = [
  "xkbcommon",
  "calloop",
] }
wayland-backend = { workspace = true, features = ["client_system"] }


# ashpd = { workspace = true }
# dirs = { workspace = true }
# futures-util = { workspace = true }
# strum = { workspace = true }
# tokio = { workspace = true }

# wgpu = { workspace = true }
