use crate::tree::Node;

fn walk<N: Node + 'static>(node: &N, v: &mut impl NodeVisitor) {
    v.visit(node);
    node.children().for_each(v);
}
fn walk_mut<N: Node + 'static>(node: &mut N, v: &mut impl NodeVisitor) {
    v.visit(node);
    node.children_mut().for_each_mut(v);
}
fn walk_with_parent<P: Node + 'static, C: Node + 'static>(
    parent: &P,
    child: &C,
    v: &mut impl NodeVisitor,
) {
    v.visit_with_parent(parent, child);
    child.children().for_each_recursive_parent(v, child);
}

#[allow(unused_variables)]
pub trait NodeVisitor {
    fn visit<N: Node + 'static>(&mut self, node: &N) {}
    fn visit_with_parent<P: Node + 'static, C: Node + 'static>(&mut self, parent: &P, child: &C) {}

    fn visit_mut<N: Node + 'static>(&mut self, node: &mut N) {}
    fn visit_with_parent_mut<P: Node + 'static, C: Node + 'static>(
        &mut self,
        parent: &P,
        child: &C,
    ) {
    }
}

/// A trait implemented for tuples of any arity, generated by a macro
pub trait NodeForEach: Send + Sync {
    fn for_each<F: NodeVisitor>(&self, f: &mut F);
    fn for_each_recursive<F: NodeVisitor>(&self, visit_node: &mut F);
    fn for_each_recursive_parent<F: NodeVisitor, T: Node + 'static>(
        &self,
        visit_node: &mut F,
        current_node: &T,
    );

    fn for_each_mut<F: NodeVisitor>(&mut self, f: &mut F);
    fn for_each_recursive_mut<F: NodeVisitor>(&mut self, visit_node: &mut F);
}
impl NodeForEach for () {
    fn for_each<F: NodeVisitor>(&self, _: &mut F) {}
    fn for_each_recursive<F: NodeVisitor>(&self, _: &mut F) {}
    fn for_each_recursive_parent<F: NodeVisitor, T: Node>(&self, _: &mut F, _: &T) {}

    fn for_each_mut<F: NodeVisitor>(&mut self, _: &mut F) {}
    fn for_each_recursive_mut<F: NodeVisitor>(&mut self, _: &mut F) {}
}
impl<A: Node + 'static> NodeForEach for (A,) {
    fn for_each<F: NodeVisitor>(&self, f: &mut F) {
        f.visit(&self.0);
    }
    fn for_each_recursive<F: NodeVisitor>(&self, f: &mut F) {
        walk(&self.0, f);
    }
    fn for_each_recursive_parent<F: NodeVisitor, T: Node + 'static>(
        &self,
        f: &mut F,
        current_node: &T,
    ) {
        walk_with_parent(current_node, &self.0, f);
    }

    fn for_each_mut<F: NodeVisitor>(&mut self, f: &mut F) {
        f.visit_mut(&mut self.0);
    }
    fn for_each_recursive_mut<F: NodeVisitor>(&mut self, f: &mut F) {
        walk_mut(&mut self.0, f);
    }
}

macro_rules! impl_for_each {
    ( $( ( $( $name:ident ),+ ) ),* ) => {
        $(
            #[allow(unused_parens)]
            impl<$( $name: Node + 'static ),+> NodeForEach for ( $( $name ),+ , ) {
                fn for_each<Func: NodeVisitor>(&self, f: &mut Func) {
                    #[allow(non_snake_case)]
                    let ( $( $name ),+ ) = self;
                    $(
                        f.visit($name);
                    )+
                }
                fn for_each_mut<Func: NodeVisitor>(&mut self, f: &mut Func) {
                    #[allow(non_snake_case)]
                    let ( $( $name ),+ ) = self;
                    $(
                        f.visit_mut($name);
                    )+
                }
                fn for_each_recursive<Func: NodeVisitor>(&self, f: &mut Func) {
                    #[allow(non_snake_case)]
                    let ( $( $name ),+ ) = self;
                    $(
                        walk($name, f);
                    )+
                }
                fn for_each_recursive_mut<Func: NodeVisitor>(&mut self, f: &mut Func) {
                    #[allow(non_snake_case)]
                    let ( $( $name ),+ ) = self;
                    $(
                        walk_mut($name, f);
                    )+
                }

                fn for_each_recursive_parent<Func: NodeVisitor, Parent: Node + 'static>(&self, f: &mut Func, current_node: &Parent) {
                    #[allow(non_snake_case)]
                    let ( $( $name ),+ ) = self;
                    $(
                        walk_with_parent(current_node, $name,  f);
                    )+
                }
            }
        )*
    };
}

// Generate impls for tuple sizes 1 through 16 (or higher if you like)
impl_for_each![
    (A, B),
    (A, B, C),
    (A, B, C, D),
    (A, B, C, D, E),
    (A, B, C, D, E, F),
    (A, B, C, D, E, F, G),
    (A, B, C, D, E, F, G, H),
    (A, B, C, D, E, F, G, H, I),
    (A, B, C, D, E, F, G, H, I, J),
    (A, B, C, D, E, F, G, H, I, J, K),
    (A, B, C, D, E, F, G, H, I, J, K, L),
    (A, B, C, D, E, F, G, H, I, J, K, L, M),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y),
    (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)
];
